# Generated by Django 4.0.1 on 2022-01-20 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now=True, verbose_name='Data de Criação')),
                ('data_edicao', models.DateTimeField(auto_now=True, verbose_name='Data de Edição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cnpj', models.CharField(blank=True, max_length=32, null=True, verbose_name='Cnpj')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia')),
                ('responsavel', models.CharField(blank=True, max_length=32, null=True, verbose_name='Responsável')),
                ('email', models.CharField(blank=True, max_length=120, null=True, verbose_name='E-mail')),
                ('matriz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresaColigada.empresa')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
