# Generated by Django 4.0.1 on 2022-01-20 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FornecedorTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now=True, verbose_name='Data de Criação')),
                ('data_edicao', models.DateTimeField(auto_now=True, verbose_name='Data de Edição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=50, null=True, verbose_name='Nome Tipo Fornecedor')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo Fornecedor',
                'verbose_name_plural': 'Tipo Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('pessoajuridica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pessoa.pessoajuridica')),
                ('id_tipo_fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_tipo_fornecedor', to='clienteFornecedor.fornecedortipo')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
            bases=('pessoa.pessoajuridica',),
        ),
    ]
