# Generated by Django 4.0.1 on 2022-01-16 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresaColigada', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now=True, verbose_name='Data de Criação')),
                ('data_edicao', models.DateTimeField(auto_now=True, verbose_name='Data de Edição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('codigo_auxiliar', models.CharField(max_length=15, verbose_name='codigo Auxiliar')),
                ('codigo_mercado', models.CharField(max_length=15, null=True, verbose_name='codigo Padrão do Mercado')),
                ('ncm', models.CharField(max_length=15, null=True, verbose_name='codigo Merco-sul')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Produtos')),
                ('imagem', stdimage.models.StdImageField(upload_to='produto/imagens', verbose_name='Imagem')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
                ('id_Empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Id_empresa_produto', to='empresaColigada.empresa')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
