# Generated by Django 4.0.1 on 2022-01-20 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresaColigada', '0001_initial'),
        ('clienteFornecedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinhaAplicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Perfil')),
            ],
            options={
                'verbose_name': 'Linha Perfil',
                'verbose_name_plural': 'Linhas Pefís',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now=True, verbose_name='Data de Criação')),
                ('data_edicao', models.DateTimeField(auto_now=True, verbose_name='Data de Edição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('codigo_auxiliar', models.CharField(max_length=15, verbose_name='codigo Auxiliar')),
                ('codigo_mercado', models.CharField(max_length=15, null=True, verbose_name='codigo Padrão do Mercado')),
                ('ncm', models.CharField(max_length=15, null=True, verbose_name='codigo Merco-sul')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Produtos')),
                ('imagem', stdimage.models.StdImageField(upload_to='produto/imagens', verbose_name='Imagem')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
                ('id_Empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Id_empresa_produto', to='empresaColigada.empresa')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProdutoPorFornecedor',
            fields=[
                ('produto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produto.produto')),
                ('id_fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_fornecedor_produto', to='clienteFornecedor.fornecedor')),
            ],
            options={
                'abstract': False,
            },
            bases=('produto.produto',),
        ),
        migrations.CreateModel(
            name='TipoVidro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now=True, verbose_name='Data de Criação')),
                ('data_edicao', models.DateTimeField(auto_now=True, verbose_name='Data de Edição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=50, null=True, verbose_name='Nome Tipo Vidro')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo vidro',
                'verbose_name_plural': 'Tipos vidros',
            },
        ),
        migrations.CreateModel(
            name='TipoPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now=True, verbose_name='Data de Criação')),
                ('data_edicao', models.DateTimeField(auto_now=True, verbose_name='Data de Edição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=50, null=True, verbose_name='Nome Tipo Perfil')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo Perfil',
                'verbose_name_plural': 'Tipos Perfís',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now=True, verbose_name='Data de Criação')),
                ('data_edicao', models.DateTimeField(auto_now=True, verbose_name='Data de Edição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=50, null=True, verbose_name='Nome Tipo')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo Componente',
                'verbose_name_plural': 'Tipos Componentes',
            },
        ),
        migrations.CreateModel(
            name='GrupoAplicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now=True, verbose_name='Data de Criação')),
                ('data_edicao', models.DateTimeField(auto_now=True, verbose_name='Data de Edição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=50, null=True, verbose_name='Nome da Aplicação')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grupo Aplicação Componentes',
                'verbose_name_plural': 'Grupos Aplicações Componentes',
            },
        ),
        migrations.CreateModel(
            name='CorVidro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now=True, verbose_name='Data de Criação')),
                ('data_edicao', models.DateTimeField(auto_now=True, verbose_name='Data de Edição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=50, null=True, verbose_name='Nome da Cor Vidro')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cor do vidro',
                'verbose_name_plural': 'Cores dos vidros',
            },
        ),
        migrations.CreateModel(
            name='CorPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now=True, verbose_name='Data de Criação')),
                ('data_edicao', models.DateTimeField(auto_now=True, verbose_name='Data de Edição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=50, null=True, verbose_name='Nome da Cor Perfil')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cor do perfil',
                'verbose_name_plural': 'Cores dos perfís',
            },
        ),
        migrations.CreateModel(
            name='CorComponentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now=True, verbose_name='Data de Criação')),
                ('data_edicao', models.DateTimeField(auto_now=True, verbose_name='Data de Edição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=50, null=True, verbose_name='Nome da Cor')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cor do Componente',
                'verbose_name_plural': 'Cores dos Componentes',
            },
        ),
        migrations.CreateModel(
            name='Vidros',
            fields=[
                ('produtoporfornecedor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produto.produtoporfornecedor')),
                ('espessura', models.IntegerField(null=True, verbose_name='Espessura')),
                ('arredondamento', models.IntegerField(null=True, verbose_name='Arredondamento')),
                ('metragem_minima', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Metragem Mínima')),
                ('id_cor_vidro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_cor_vidro', to='produto.corvidro')),
                ('id_tipo_vidro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_tipo_vidro', to='produto.tipovidro')),
            ],
            options={
                'verbose_name': 'Vidro',
                'verbose_name_plural': 'Vidros',
            },
            bases=('produto.produtoporfornecedor',),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('produtoporfornecedor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produto.produtoporfornecedor')),
                ('comprimento_padrão', models.IntegerField(null=True, verbose_name='Comprimento')),
                ('estoque', models.IntegerField(null=True, verbose_name='estoque')),
                ('id_cor_perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_cor_pefil', to='produto.corperfil')),
                ('id_linha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_linha_perfil', to='produto.linhaaplicacao')),
                ('id_tipo_perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_tipo_perfil', to='produto.tipoperfil')),
            ],
            options={
                'verbose_name': 'Pefil',
                'verbose_name_plural': 'Perfís',
            },
            bases=('produto.produtoporfornecedor',),
        ),
        migrations.CreateModel(
            name='PefilReclassificao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(null=True, verbose_name='Quantidade')),
                ('comprimento_padrão', models.IntegerField(null=True, verbose_name='Comprimento')),
                ('id_perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_reclassificacao_perfil', to='produto.perfil')),
            ],
            options={
                'verbose_name': 'Perfil Reclassificado',
                'verbose_name_plural': 'Perfis Reclassificaos',
            },
        ),
        migrations.CreateModel(
            name='ComponentesAcessorios',
            fields=[
                ('produtoporfornecedor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produto.produtoporfornecedor')),
                ('id_cor_componentes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_cor_componentes', to='produto.corcomponentes')),
                ('id_grupo_aplicacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_grupo_componentes', to='produto.grupoaplicacao')),
                ('id_tipo_componentes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_tipo_componentes', to='produto.tipo')),
            ],
            options={
                'verbose_name': 'Vidro',
                'verbose_name_plural': 'Vidros',
            },
            bases=('produto.produtoporfornecedor',),
        ),
        migrations.CreateModel(
            name='BeneficiamentoVidro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now=True, verbose_name='Data de Criação')),
                ('data_edicao', models.DateTimeField(auto_now=True, verbose_name='Data de Edição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Beneficiamento')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id_vidro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_beneficiamento_vidro', to='produto.vidros')),
            ],
            options={
                'verbose_name': 'Beneficiamento',
                'verbose_name_plural': 'Beneficiamentos',
            },
        ),
    ]
